#!/bin/sh
# Pushes a new version to PyPi.

cd "$(dirname "$0")/.."

if ./script/check_release; then
    rm -rf dist
    uv build
    uv publish --check-url https://pypi.org/simple dist/*
else
    echo "check_release failed. Aborting release."
fi
